### PR TITLE
Fix Noise after Cold Boot (#135)

### LINKED ISSUE #135: Loud Noise at first playback
Whenever an esp32-audio-kit 2.2 or lyrat 4.3 board streams for the first time since it was connected to power, a loud noise is audible before the stream starts. When I restart the boards via the "rst" button, this issue does not occur. I think the issue can also reoccur even when the board stayed connected to power, but "crashed".

### PR DESCRIPTION
**Pull request by blattm**
I added some code to play silence before snapcast and player are initialized. This fixes #135, the noise issue for both Lyrat 4.3 and Esp-32 Audio Kit 🎉.

Although the noise is gone, I'm pretty sure that this is not an ideal implementation. So I'd be more than happy for feedback :)

### CODE REVIEW

**Comment by blattm** [comment]
Sure! I will try it today :)

**Comment by blattm** [comment]
I noticed something: The noise is exactly as long as the latency buffer duration.  So I think the real fix would be to ensure correct buffer initialization.

**Comment by CarlosDerSeher** [comment]
No idea where the clicking could come from.

But here is another thought, maybe it is related to i2s pins are in an undefined state after boot? Audio board is initialized but i2s pins aren't already. Maybe just setting them to high or low will be enough already? Or if not, just initializing i2s before audio board doesn't help?

**Comment by luar123** [comment]
Latest master compiles fine with idf v5.5.1 (did not test with lyrat).
I think you need to run `fullclean` after switching idf version before `build`.

**Comment by blattm** [comment]
Thank you for the input :)
I did some tests and can confirm: The issue was introduced in db0f9732b2f5dcddce8bd2bb309377da878d4a11, and is not resolved by simply using idf v5.5.1.

Also i found out:
- There is nothing in the documentation / changelogs of idf v5 indicating that we are using the interface in a wrong way
- `i2s_channel_init_std_mode` is where the noise starts, not the preload function
- The section in `main.c` that sets gpio pins and is marked with  `// ensure there is no noise from DAC` is only a temporary fix. It seems like the preload function causes the io pins to be claimed by the peripheral, undoing the fix. But the upside is: when we stream silence or enable the i2s, setting gpio pins is not necessary.
- muting/disabling dac does not help

Because I were unable to find a "real" fix, I stuck with the playing silence workaround. The workaround uses the existing tx channel and is executed immediately after the first I2S initialization to eliminate even very short periods of noise.
I think it works pretty well overall.

**Comment by CarlosDerSeher** [comment]
could you try to set `auto_clear = true` in `struct i2s_chan_config_t` ? shouldn't this effectively send silence all the time when i2s is enabled?

**Comment by blattm** [comment]
I didn't change any existing `auto_clear` settings, neither in the temporary setup in the main, nor in the player (where it is currently set to false), because it didn't help with the original noise issue. But I ran some more tests to see whether setting it to true in the player helps with the popping sound. I also tested preloading with zeros once instead of streaming silence. 

The results (all tests without gpio hack and with es8388 fix. One power cycle before counting pops):
silence streaming -> basically perfect, no audible pop
no silence, auto clear true -> pops
no silence, but opening stream and waiting -> pops
no slience, but opening stream, waiting + auto clear true -> pops
just waiting + auto clear true ->  pops
preloading zeros on the first player_setup_i2s (which never gets used, btw) -> pops
preloading zeros as before, then enabling, waiting and disabling tx -> pops
preloading zeros instead of payload + auto clear -> pops
preloading zeros instead of payload -> pops

I also tested implicitly preloading with silence by streaming sending silence from the snapserver -> still pops

So there is still no solution performing better than priming with silence. I don't know why it helps. But it does, by a lot. I really wish that one of the more "sensible" solutions worked... :/

**Comment by CarlosDerSeher** [comment]
I see. I will have to try this myself, so be patient with me. Do you use line out or the PA on lyrat v4.3? Are you seeing this with both?

**Comment by CarlosDerSeher** [comment]
Sure, i like this idea. Maybe add a known issues section to the Readme and explain why this piece of code is there.

**Comment by blattm** [comment]
Alright, I added some info about the fix in the readme.
What about the clicks and pops, though? Should I include the streaming of silence, which for some reason gets rid of some clicks and pops in this PR? I would, of course, also describe this in the readme. Or would you prefer this to be dealt with in a separate issue/PR?

Btw, I tried cherry-picking my commits onto the develop branch, and it works over there as well :)

File: main/main.c [hunk 1]
```diff
@@ -2603,23 +2603,24 @@ void app_main(void) {
...
+  //       .pull_up_en = GPIO_PULLUP_DISABLE,
+  //       .pull_down_en = GPIO_PULLDOWN_DISABLE,
+  //       .intr_type = GPIO_INTR_DISABLE,
+  //   };
+  //   gpio_config(&gpioCfg);
+  //   gpio_set_level(pin_config0.mck_io_num, 0);
+  //   gpio_set_level(pin_config0.data_out_num, 0);
+  //   gpio_set_level(pin_config0.bck_io_num, 0);
+  //   gpio_set_level(pin_config0.ws_io_num, 0);
+  // }
```
Comment (CarlosDerSeher) [inline main/main.c]: One more thing. Could you remove this instead of comment?
