### PR TITLE
Kalmanfilter

### LINKED ISSUE #148: Sync is sometimes drifting a few milli seconds
Typically, the sync is within 200-500µs, drifting a little bit around. Even if it is off by a few ms after boot-up it will recover fast. But, sometimes there is an 2-4ms offset or it is starting good and then drifting away.
If I remember correctly that was not happening 2 years ago, but I could be wrong.
(I measured sync with two esp32+pcm5102a)

The guys from esphome are using a Kalmann filter for their new resonate player implementations and claim that the sync is much better than with a median filter: https://github.com/Resonate-Protocol/time-filter/tree/main
Benefits are that the uncertainty is taken into account and it will compensate for a constant drift.
Maybe that is worth a try, it should be fairly easy to implement. Just needs a C wrapper and some modifications to the get_server_now and insert_latency functions.

> // Update filter with computed offset and uncertainty from NTP exchange
> // measurement: ((T2-T1)+(T3-T4))/2 in microseconds
> // max_error: ((T4-T1)-(T3-T2))/2 in microseconds
> // time_added: Client timestamp when measurement was taken in microseconds
> void update(int64_t measurement, int64_t max_error, int64_t time_added);

measurement: ((T2-T1)+(T3-T4))/2 in microseconds = `-tmpDiffToServer` = `-(trx - tdif) / 2`
max_error: ((T4-T1)-(T3-T2))/2 in microseconds = `(tdif + trx) / 2`

### PR DESCRIPTION
**Pull request by luar123**
Use Kalman filter instead of median.
You can also set the base branch to develop if you want to merge directly.

There are some other changes included: logs, task priority/affinity, default sdkconfig for esp32s3, filter size and reset_latency_buffer handling. Not sure if everything is need, but for reverting I would need to run more tests.

The resetting of latency_buffer should be further improved, I plan to look into this when reworking the inter-task communication (that's what I wanted to do today in the first place...).

Fix #148

### CODE REVIEW

File: components/lightsnapcast/player.c [hunk 1]
```diff
@@ -625,25 +631,36 @@ int32_t latency_buffer_full(bool *is_full, TickType_t wait) {
 /**
  *
  */
-int32_t get_diff_to_server(int64_t *tDiff) {
-  static int64_t lastDiff = 0;
+int32_t get_diff_to_server(int64_t *tDiff, int64_t now) {
+  static double lastDiff = 0;
```
Comment (CarlosDerSeher) [inline components/lightsnapcast/player.c]: Won't you need to reset those static variables at any time?

File: components/timefilter/component.mk
Comment (CarlosDerSeher) [inline components/timefilter/component.mk]: We won't need this.

File: main/main.c [hunk 2]
```diff
@@ -480,7 +480,7 @@ static void http_get_task(void *pvParameters) {
   int rc1 = ERR_OK, rc2 = ERR_OK;
   struct netbuf *firstNetBuf = NULL;
   uint16_t len;
-  uint64_t timeout = FAST_SYNC_LATENCY_BUF;
```
Comment (CarlosDerSeher) [inline main/main.c]: Don't you need the initial fast time message exchange anymore?

File: components/lightsnapcast/player.c [hunk 3]
```diff
@@ -486,22 +492,24 @@ int8_t player_get_snapcast_settings(snapcastSetting_t *setting) {
 /**
  *
  */
-int32_t player_latency_insert(int64_t newValue) {
-  int64_t medianValue;
-
-  medianValue = MEDIANFILTER_Insert(&latencyMedianFilter, newValue);
+int32_t player_latency_insert(int64_t newValue, int64_t max_error, int64_t time_added) {
+  TIMEFILTER_Insert(&latencyTimeFilter, newValue, max_error, time_added);
+  int64_t last_update_ = latencyTimeFilter.last_update_;
```
[the remark this answers is not in the document]
Comment (luar123) [reply components/lightsnapcast/player.c]: Wrong code style. I just kept the style of the original implementation, but I can change it.

[the remark this answers is not in the document]
Comment (CarlosDerSeher) [reply components/lightsnapcast/player.c]: No I was just wondering. Did you add a link to the original source somewhere? If not please do

File: components/lightsnapcast/player.c (hunk 1 above)
Comment (luar123) [reply components/lightsnapcast/player.c]: Not sure if I understand your question?
